#!/bin/bash

wget http://codingismycraft.com/wp-content/uploads/2013/03/the-c-programming-language.jpe
wget http://codingismycraft.com/wp-content/uploads/2013/03/the-c-plus-plus-programming-language.jpe
wget http://codingismycraft.com/wp-content/uploads/2013/03/effective-c-plus-plus.jpe
wget http://codingismycraft.com/wp-content/uploads/2013/03/more-effective-c-plus-plus.jpe
wget http://codingismycraft.com/wp-content/uploads/2013/03/design-patterns-book.jpe
wget http://codingismycraft.com/wp-content/uploads/2013/03/the-art-of-computer-programming.jpe
wget http://codingismycraft.com/wp-content/uploads/2013/03/moderen-c-plus-plus-design.jpe
wget http://codingismycraft.com/wp-content/uploads/2013/03/unix-network-programming.jpe
wget http://codingismycraft.com/wp-content/uploads/2013/03/the-unix-programming-environment.jpe
wget http://codingismycraft.com/wp-content/uploads/2013/03/python-algorithms.jpe
wget http://codingismycraft.com/wp-content/uploads/2013/03/learning-python.jpe
wget http://codingismycraft.com/wp-content/uploads/2013/03/the-quick-python-book.jpe
wget http://codingismycraft.com/wp-content/uploads/2013/03/artificial-inteligence-with-list.jpe
wget http://codingismycraft.com/wp-content/uploads/2013/03/structure-and-interpretation-of-computer-programs.jpe
wget http://codingismycraft.com/wp-content/uploads/2013/03/artificial-inteligence-with-list.jpe
wget http://codingismycraft.com/wp-content/uploads/2013/03/structure-and-interpretation-of-computer-programs.jpe
wget http://codingismycraft.com/wp-content/uploads/2013/03/python-cookbook.jpe
wget http://codingismycraft.com/wp-content/uploads/2013/03/the-python-standard-library.jpe
wget http://codingismycraft.com/wp-content/uploads/2013/03/modern-artificial-intelligence.jpe
wget http://codingismycraft.com/wp-content/uploads/2013/03/writting-compileres-and-interpreters.jpe
wget http://codingismycraft.com/wp-content/uploads/2013/03/C-sharp-in-depth.jpe
wget http://codingismycraft.com/wp-content/uploads/2016/09/The-Logic-of-Scientific-Discovery.jpg
wget http://codingismycraft.com/wp-content/uploads/2016/09/conjectures-refutations.jpg
wget http://codingismycraft.com/wp-content/uploads/2016/09/open-society-and-enemies.jpg
wget http://codingismycraft.com/wp-content/uploads/2016/09/the-poverty-of-historism.jpg
wget http://codingismycraft.com/wp-content/uploads/2016/09/what-is-life.jpg
wget http://codingismycraft.com/wp-content/uploads/2016/09/tractatus.jpg
wget http://codingismycraft.com/wp-content/uploads/2016/09/organon.jpg
wget http://codingismycraft.com/wp-content/uploads/2016/09/ancient-greek-philosophy.jpg
wget http://codingismycraft.com/wp-content/uploads/2016/09/structure-of-scientific-revolutions.jpg
wget http://codingismycraft.com/wp-content/uploads/2016/09/plato-the-republic.jpg
wget http://codingismycraft.com/wp-content/uploads/2016/09/aristotele-physics.jpg
wget http://codingismycraft.com/wp-content/uploads/2016/09/Syntactic-Structures.jpg
wget http://codingismycraft.com/wp-content/uploads/2016/09/img-to-have-or-to-be.jpg
wget http://codingismycraft.com/wp-content/uploads/2016/09/human-destructiveness.jpg
wget http://codingismycraft.com/wp-content/uploads/2016/09/the-sane-society.jpg
wget http://codingismycraft.com/wp-content/uploads/2016/09/Thinking_Fast_and_Slow.jpg
wget http://codingismycraft.com/wp-content/uploads/2016/09/The_Black_Swan_Nassim_Nicholas_Taleb_Book.jpg
wget http://codingismycraft.com/wp-content/uploads/2016/09/tipping-point.jpg
